### PR TITLE
feat/tailwind に移行する

### PR DESCRIPTION
**Pull request by anko9801**
### **User description**
fix: #139

___

### **PR Type**
enhancement, dependencies

___

### **Description**
- Tailwind CSSを導入し、WindiCSSを削除しました。
- 各コンポーネントとページでTailwind CSSクラスを適用しました。
- `vite.config.ts`からWindiCSSプラグインを削除しました。
- `tailwind.config.js`を追加し、カスタムカラーとタイポグラフィプラグインを定義しました。
- `postcss.config.js`を追加し、Tailwind CSSとautoprefixerを設定しました。
- `package.json`を更新し、Tailwind CSS関連の依存関係を追加し、WindiCSS関連の依存関係を削除しました。
- MSWのバージョンを2.4.1に更新しました。

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>20 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>TransactionFilters.vue</strong><dd><code>Migrate TransactionFilters to Tailwind CSS</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/components/transactions/TransactionFilters.vue

<li>Tailwind CSS classes applied to elements.<br> <li> Adjusted width classes for buttons and divs.<br>

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-880cad5beac402e0fa97e1c9dcf583133275e5196dcdf010ebe84b14f7415d03">+6/-6</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>TransactionItem.vue</strong><dd><code>Migrate TransactionItem to Tailwind CSS</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/components/transactions/TransactionItem.vue

<li>Tailwind CSS classes applied to elements.<br> <li> Adjusted width classes for divs.<br>

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-2a1839f0b4003e016bf181b2756a4e1f8dceddc7e48d5ebd0feff5c7ba2e2e70">+6/-6</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>PaginationBar.vue</strong><dd><code>Update PaginationBar with Tailwind CSS</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/components/shared/PaginationBar.vue

- Adjusted width classes for pagination buttons.

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-86c42bd665b2cb555edb359098b6d022639628472880d96bf55ef42e51440bf9">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>GroupsPage.vue</strong><dd><code>Apply Tailwind CSS to GroupsPage</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/pages/GroupsPage.vue

- Updated minimum width using Tailwind CSS.

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-18ea49f0775c283b38afa95b22a0a5aca50ef20a12bb06dd80024c499d3249ed">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>TransactionsPage.vue</strong><dd><code>Apply Tailwind CSS to TransactionsPage</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/pages/TransactionsPage.vue

- Updated minimum width using Tailwind CSS.

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-72ef8651ea9efcd5a9c0fbdca230b71164c085103d1784b270d2999816d7367b">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>RequestsPage.vue</strong><dd><code>Apply Tailwind CSS to RequestsPage</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/pages/RequestsPage.vue

- Updated minimum width using Tailwind CSS.

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-e6f36fe539a726e1445fc38e5f462e9ad96efebd1eaa093ba22d3cb8836e0da9">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>InputSelectMultiple.vue</strong><dd><code>Update InputSelectMultiple with Tailwind CSS</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/components/shared/InputSelectMultiple.vue

- Adjusted width calculation for input select.

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-c0a069c4932d67da14cc3d49da3dc089798d5dda6d0892a12dc8f523682e3331">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>RequestFilters.vue</strong><dd><code>Update RequestFilters with Tailwind CSS</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/components/requests/RequestFilters.vue

- Adjusted margin-left for span elements.

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-23037307eec60cf109320ea4f187a3fdec909648371981d968457ac2ed7fae71">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>InputSelectSingle.vue</strong><dd><code>Update InputSelectSingle with Tailwind CSS</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/components/shared/InputSelectSingle.vue

- Adjusted width calculation for input select.

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-486e182fefebefa1b775ed697f500e46bf073425f712c5067aff366e362f2bd4">+2/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>NewTransactionPage.vue</strong><dd><code>Apply Tailwind CSS to NewTransactionPage</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/pages/NewTransactionPage.vue

- Updated minimum width using Tailwind CSS.

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-97dc29bdabe844b33e22993ae18741b5ba03f55a02feb6047a51ee6ba93609f6">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>AdminPage.vue</strong><dd><code>Apply Tailwind CSS to AdminPage</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/pages/AdminPage.vue

- Updated minimum width using Tailwind CSS.

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-697ec417d3f0fff9589ecbb65c23e0f82d3741ba9f49e4a3ac41861a22628f42">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>RequestDetailPage.vue</strong><dd><code>Update RequestDetailPage with Tailwind CSS</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/pages/RequestDetailPage.vue

- Adjusted height for div using Tailwind CSS.

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-7bceb02bc8dd2209b91d736fe97f867bc48dfaf28e6b31db3d1b304042e7f723">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>NewRequestPage.vue</strong><dd><code>Apply Tailwind CSS to NewRequestPage</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/pages/NewRequestPage.vue

- Updated minimum width using Tailwind CSS.

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-80ca3c77dec16e2bd5535a97d4e52402d86819095aab7ddba62a0d42cb680250">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>NewGroupPage.vue</strong><dd><code>Apply Tailwind CSS to NewGroupPage</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/pages/NewGroupPage.vue

- Updated minimum width using Tailwind CSS.

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-9874c53ccd30d720f77fcba00975c332a913ff985b012bada0c9b4312683f7cd">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>RequestContent.vue</strong><dd><code>Update RequestContent with Tailwind CSS</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/components/requestDetail/RequestContent.vue

- Adjusted margin-left for div using Tailwind CSS.

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-5035b78e2c2325486613aa282884db081c49d86d7a9f492e9842739650cc4e40">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>CommentLog.vue</strong><dd><code>Update CommentLog with Tailwind CSS</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/components/requestDetail/CommentLog.vue

- Adjusted margin-left for div using Tailwind CSS.

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-dbc2180feea426678f3dc94efe410d1d8c84d276b433a94ee2dc5eb94a63bde2">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>PageLink.vue</strong><dd><code>Simplify PageLink component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/components/shared/PageLink.vue

- Removed block class from router-link.

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-56b635dafaa2f74f546b48e6b7c3b392107c96fc9dbfe6dd424efa5f31b379fa">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>tailwind.config.js</strong><dd><code>Add Tailwind CSS configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tailwind.config.js

<li>Added Tailwind CSS configuration file.<br> <li> Defined custom colors and typography plugin.<br>

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-ddc1067f080930bc48865f4660316a14b21bbc9f9ba85975ce8479342b983d2e">+32/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>postcss.config.js</strong><dd><code>Add PostCSS configuration for Tailwind CSS</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

postcss.config.js

- Added PostCSS configuration with Tailwind CSS and autoprefixer.

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-05ed1c7f99e45b485708115502a1e0f28c8547e9a9a29c1b8664f79103cf7873">+6/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>main.css</strong><dd><code>Integrate Tailwind CSS into main styles</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/styles/main.css

- Added Tailwind CSS base, components, and utilities.

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-25d6a3ff17a1c8acb9b8e63e990597d94ef65730407b2e171edbf73b7515df3d">+4/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Dependencies</strong></td><td><details><summary>3 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>vite.config.ts</strong><dd><code>Remove WindiCSS from Vite configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

vite.config.ts

- Removed WindiCSS plugin.

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-6a3b01ba97829c9566ef2d8dc466ffcffb4bdac08706d3d6319e42e0aa6890dd">+1/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>mockServiceWorker.js</strong><dd><code>Update MSW version in mockServiceWorker</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

public/mockServiceWorker.js

- Updated MSW package version.

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-9b67b1564153a29cf70395735ad6a98050c0b64868ca3f7c8feafe8bc6cf8f52">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>package.json</strong><dd><code>Update package.json for Tailwind CSS migration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

package.json

<li>Added Tailwind CSS and related dependencies.<br> <li> Removed WindiCSS and related dependencies.<br>

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519">+5/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr><tr><td><strong>Additional files (token-limit)</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>package-lock.json</strong><dd><code>...</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

package-lock.json

...

</details>

  </td>
  <td><a href="https://github.com/traPtitech/Jomon-UI/pull/290/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519">+1604/-162</a></td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by reiroop** [comment]
LGTMです
一応Code Suggestionsを見ていただきたいのと、僕だとわからないことも多いのでめふもさんにもレビューをお願いしたいかもです

**Review by mehm8128 — APPROVED** [review]
内容的には問題なさそうですが、今他に結構PRが出てる状態なので、マージするタイミングとかは気をつけた方がよさそうです

**Pull request merged**
